name: Continuous benchmarking

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

on:
  issue_comment:
    types: ['created', 'edited']

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  steps:
    debug:
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo "$GITHUB_CONTEXT"
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}

